**Goal**
1. Indexing & selection
2. Slicing

In [1]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# grab value at a particluar index
arr[8]

np.int64(8)

In [ ]:
# grab values from start to end index - start including and stop excluding
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0,5]

In [ ]:
arr[:5]

In [ ]:
arr[1:]

In [4]:
arr[1:5:2]

array([1, 3])

**Broadcast**

In [6]:
# change the values from start to stop index to a given new values, ex: change the values at from 0 to 4 index to 100 
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

**Slicing of an area changes the original array as well, even if we assign the sliced array to a new variable and then change only the sliced array.**

In [22]:
orig_array1 = np.arange(11)
orig_array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
slice_of_array = orig_array1[:5]
slice_of_array

array([0, 1, 2, 3, 4])

In [28]:
slice_of_array[:4]=90
slice_of_array

array([ 90,  90,  90,  90, 100])

In [29]:
orig_array1

array([ 90,  90,  90,  90, 100,   5,   6,   7,   8,   9,  10])

**To safely slice (and prevent original array from changing), use copy function to craete slice using copy**

In [30]:
orig_array2=np.arange(11)
orig_array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
slice_by_copy = orig_array2.copy()
slice_by_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
slice_by_copy[:5] = 85
slice_by_copy

array([85, 85, 85, 85, 85,  5,  6,  7,  8,  9, 10])

In [44]:
orig_array2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**2D opeartions**

In [45]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [46]:
arr_2d.shape

(3, 3)

In [47]:
arr_2d[0]

array([ 5, 10, 15])

**Accessing values at 2D index:
can give as [r][c] or [r,c]**

In [48]:
arr_2d[1][1]

np.int64(25)

In [50]:
arr_2d[1,1]

np.int64(25)

In [51]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [66]:
# [start row:end row(excluding), start col:end col(excluding):step]
arr_2d[:2,2:]

array([[15],
       [30]])

In [60]:
arr_2d[:1,2:]

array([[15]])