**Goal**
1. Create NumPy Arrays (multi-dimensional)
2. Built-in Functions
3. Generating random data
4. Key attributes of NumPy Arrays

**1. Create NumPy Arrays**

In [106]:
# Create a simple python list
mylist = [1,2,3]
type(mylist)
mylist

[1, 2, 3]

In [107]:
# !pip install numpy
import numpy as np

In [108]:
# Create a NumPy Array - single dimension

my_np_array=np.array(mylist)
# type(my_np_array)
my_np_array

array([1, 2, 3])

In [109]:
# Create a simple 2-D list (matrix)

my_2d_matrix = [[1,2,3],[4,5,6],[7,8,9]]
# type(my_2d_matrix)
my_2d_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [110]:
# Create a NumPy Array - 2-dimension

my_np_matrix=np.array(my_2d_matrix)
my_np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**2. Built-in Functions**

In [111]:
''' Create a numpy array by give start and end value along with step-size - using function "arange(start, stop, step)".
    Stop is not inclusive
'''

np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [112]:
''' Create a numpy array that has all 0 items - using function "zeros(number of items)".
 All the values are "float" in this hence a trailing "." 
'''

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [113]:
# 2-d array of zeros - zeros ((row, cols)
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [114]:
# array of all "1"s
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
# linearly spaced array : linspace(start, stop, space) i.e. how many equally spaced numbers between start stop
# stop or endspace is included in this function by default. so 0-10 means 11 numbers.

np.linspace(0,5,21)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [116]:
len(np.linspace(0,5,21))

21

In [117]:
# Create Identity matrix - its always a square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**3. Generating random data**

In [118]:
# Generate random data array using random.rand(size) - populates randam values from a Uniform Distribution over (0,1) which means all the numbers have the same likelihood of being picked
np.random.rand(5)

array([0.69772882, 0.2160895 , 0.97627445, 0.00623026, 0.25298236])

In [119]:
# Generate 2D data arary using random.rand(row,col) - Uniform Distribution
np.random.rand(2,3)

array([[0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224]])

In [120]:
# Random numbers from a standard normal distribution - i.e. where mean = 0 and variance = 1 which means values closer to 0 are more likely to appear
np.random.randn(10)

array([-0.48492332, -0.12066567, -0.0788265 ,  0.56373477, -0.18040236,
        0.20218012,  0.16951775, -0.71522547,  0.52533388, -0.74738768])

In [121]:
# generates interger random values
np.random.randint(0,6,2)

array([2, 1])

In [122]:
# seed gives a particular set of same random numbers. same seed will always return same set of random numbers
np.random.seed(4)
np.random.rand(4)

array([0.96702984, 0.54723225, 0.97268436, 0.71481599])

**4. Key Attributes**

In [123]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [124]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [125]:
# you cant fit 25 number in 5x4 size
# arr.reshape(5,4)

In [126]:
ranarr=np.random.randint(0,101,10)
ranarr

array([50,  9, 58, 94, 55, 55, 57, 36, 50, 44])

In [127]:
# attribute not method
ranarr.dtype

dtype('int64')

In [128]:
ranarr.shape

(10,)

In [129]:
ranarr.reshape(5,2)

array([[50,  9],
       [58, 94],
       [55, 55],
       [57, 36],
       [50, 44]])

In [130]:
ranarr.shape

(10,)

In [131]:
ranarr

array([50,  9, 58, 94, 55, 55, 57, 36, 50, 44])

In [132]:
ranarr=ranarr.reshape(2,5)
ranarr

array([[50,  9, 58, 94, 55],
       [55, 57, 36, 50, 44]])

In [133]:
ranarr.shape

(2, 5)

In [134]:
ranarr.max()

np.int64(94)

In [135]:
ranarr.argmax()

np.int64(3)

In [136]:
ranarr.min()

np.int64(9)

In [137]:
ranarr.argmin()

np.int64(1)

In [ ]:
# Random choice from array
arr = np.array([10, 20, 30, 40])
np.random.choice(arr, size=3)  # Randomly pick 3 elements

# Shuffle
np.random.shuffle(arr)  # Shuffles in-place

# Random permutation
np.random.permutation(arr)  # Returns shuffled copy


In [ ]:
### New API (Recommended) introduced in 1.17+

# Create a generator
rng = np.random.default_rng(seed=42)

# All operations similar but through generator
rng.random(3)              # Instead of rand()
rng.integers(0, 10, size=5) # Instead of randint()
rng.normal(50, 10, size=100)
rng.choice(arr, size=3)

# Advantage: Better for parallel code, each generator is independent
rng1 = np.random.default_rng(1)
rng2 = np.random.default_rng(2)  # Independent from rng1


### Common Distributions


rng = np.random.default_rng(42)

# Binomial (n trials, probability p)
rng.binomial(n=10, p=0.5, size=1000)

# Poisson
rng.poisson(lam=5, size=1000)

# Exponential
rng.exponential(scale=2.0, size=1000)

# Beta distribution
rng.beta(a=2, b=5, size=1000)