**Goal**
1. Create NumPy Arrays (multi-dimensional)
2. Built-in Functions
3. Generating random data
4. Key attributes of NumPy Arrays

**1. Create NumPy Arrays**

In [9]:
# Create a simple python list
mylist = [1,2,3]
type(mylist)
mylist

[1, 2, 3]

In [ ]:
# !pip install numpy
import numpy as np

In [ ]:
# Create a NumPy Array - single dimension

my_np_array=np.array(mylist)
# type(my_np_array)
my_np_array

array([1, 2, 3])

In [ ]:
# Create a simple 2-D list (matrix)

my_2d_matrix = [[1,2,3],[4,5,6],[7,8,9]]
# type(my_2d_matrix)
my_2d_matrix

list

In [14]:
# Create a NumPy Array - 2-dimension

my_np_matrix=np.array(my_2d_matrix)
my_np_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**2. Built-in Functions**

In [ ]:
''' Create a numpy array by give start and end value along with step-size - using function "arange(start, stop, step)".
    Stop is not inclusive
'''

np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [ ]:
''' Create a numpy array that has all 0 items - using function "zeros(number of items)".
 All the values are "float" in this hence a trailing "." 
'''

np.zeros(5)

array([0., 0., 0., 0., 0.])

In [21]:
# 2-d array of zeros - zeros ((row, cols)
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# array of all "1"s
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
# linearly spaced array : linspace(start, stop, space) i.e. how many equally spaced numbers between start stop
# stop or endspace is included in this function by default. so 0-10 means 11 numbers.

np.linspace(0,5,21)


array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [29]:
len(np.linspace(0,5,21))

21

In [33]:
# Create Identity matrix - its always a square matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Generating random data**